    name: SA_P3 CI

    on:
        push:
            branches:
                - feature/test
        
    jobs:
        build:
            runs-on: ubuntu-latest

            strategy:
                matrix:
                    node-version:
                        - 21.7.0

            #Clona el codigo en el workflow
            steps:
                - name: Checkout and copy code to workflow
                  uses: actions/checkout@v2

                - name: Configurar Node.js ${{ matrix.node-version }}
                  uses: actions/setup-node@v2
                  with:
                    node-version: ${{ matrix.node-version }}

                - name: Install && Build Microservice age
                  run: |
                    cd age_microservice/
                    npm run build
                
                - name: Install && Build Microservice gender
                  run: |
                    cd gender_microservice/
                    npm run build
                
                - name: Install && Build microservice name
                  run: |
                    cd name_microservice/
                    npm run build



