name: SA_P3 CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_stage:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: production

    steps:      
      # Configurar entorno de produccion
      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV
        
      - name: Display Environment
        run: | 
          echo "Environment: $ENVIRONMENT"  

      - name: Replace image name in k8s config
        run: |
          for file in k8s/*.yaml; do
            envsubst '${ENVIRONMENT}' < "$file" > "${file%.yaml}.temp"
            mv "${file%.yaml}.temp" "$file"
          done      

      # Configurar credenciales de Google Cloud Platform
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Kubernets
      - name: Deploy to GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: carbon-ray-415302
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
          CLUSTER_NAME: cluster-production
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/

